services:
  app:
    container_name: neverflat-app
    image: ghcr.io/zentrixlab/neverflat:latest
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - '127.0.0.1:3005:3000'
    environment:
      NODE_ENV: production
      LOG_DESTINATION: ${LOG_DESTINATION:-console}
      APP_VERSION: ${APP_VERSION:-1.0.0}
    networks:
      - default
      - shared-proxy

networks:
  shared-proxy:
    external: true
