export enum EnvironmentVariableKey {
  LOG_DESTINATION = 'LOG_DESTINATION',
  APP_ENVIRONMENT = 'APP_ENVIRONMENT',
  DATABASE_URL = 'DATABASE_URL',
  BUGSNAG_API_KEY = 'BUGSNAG_API_KEY',
  FILE_STORAGE = 'FILE_STORAGE',
  STATIC_RESOURCES = 'STATIC_RESOURCES',
}
