name: Deploy [AppName] to Development

on:
  push:
    branches:
      - development

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Generate .env
        run: |
          cat <<EOF > .env
          DB_USER=${{ secrets.DB_USER }}
          DB_PASS=${{ secrets.DB_PASS }}
          DB_NAME=${{ secrets.DB_NAME }}
          DATABASE_URL="postgresql://\${DB_USER}:\${DB_PASS}@db:5432/${DB_NAME}?schema=public"
          APP_ENVIRONMENT="staging"
          JWT_ACCESS_SECRET=${{ secrets.JWT_ACCESS_SECRET }}
          JWT_REFRESH_SECRET=${{ secrets.JWT_REFRESH_SECRET }}
          FILE_STORAGE=${{ secrets.FILE_STORAGE }}
          LOG_DESTINATION=${{ secrets.LOG_DESTINATION }}
          APP_VERSION=${{ secrets.APP_VERSION }}
          BUGSNAG_API_KEY=${{ secrets.BUGSNAG_API_KEY }}
          REDIS_HOST=${{ secrets.REDIS_HOST }} 
          REDIS_PORT=${{ secrets.REDIS_PORT }}
          BULLBOARD_USER=${{ secrets.BULLBOARD_USER }}
          BULLBOARD_PASS=${{ secrets.BULLBOARD_PASS }}
          BULLBOARD_ROUTE=${{ secrets.BULLBOARD_ROUTE }}

          EOF

      - name: Copy to server via SCP
        uses: appleboy/scp-action@v0.1.5
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          source: '.'
          target: ~/APP/DEPLOY/BACKEND

      - name: SSH & (re)deploy
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          script: |
            set -euo pipefail

            BASE=~/APP
            RELEASE=app_name
            DEPLOY_DIR=$BASE/DEPLOY/$RELEASE
            LIVE_DIR=$BASE/BACKEND/$RELEASE
            UPLOADS_DIR=$BASE/uploads
            mkdir -p $UPLOADS_DIR
            chown -R $(whoami):$(whoami) $UPLOADS_DIR
            docker-compose -f $LIVE_DIR/docker-compose.yml down --remove-orphans || true
            rm -rf $LIVE_DIR
            mv $DEPLOY_DIR $LIVE_DIR
            ln -sfn $UPLOADS_DIR $LIVE_DIR/uploads
            cd $LIVE_DIR
            docker-compose pull || true
            echo "Pruning remote build cache older than 24h…"
            docker builder prune --all --force --filter "until=24h" || true
            echo "Build cache pruned."
            docker-compose up -d --build
